### PR TITLE
Add agent and curriculum names to logged info

### LINKED ISSUE #297: Log files do not store agent name
Common use of tella will be multiple agents on identical curricula. It is not currently possible (unless I missed it?) to determine which agent is associated with a log file after the fact.

### PR DESCRIPTION
**Pull request by ginoperrotta**
Resolves #297

### CODE REVIEW

**Comment by coreylowman** [comment]
That's easy! 😄 Any thoughts on changing directory structure/name? e.g we could change the log directory to be `./<root>/<agent name>-<curriculum name>/...`

**Comment by ginoperrotta** [comment]
> That's easy! 😄 Any thoughts on changing directory structure/name? e.g we could change the log directory to be `./<root>/<agent name>-<curriculum name>/...`

That seems like a good idea. Do you think it is better to be agent-curriculum or curriculum-agent?

**Comment by cash** [comment]
What happens if I run the same curriculum/agent pair more than once?

**Comment by coreylowman** [comment]
> That seems like a good idea. Do you think it is better to be agent-curriculum or curriculum-agent?

Not sure if it makes a difference, but I think my vote is curriculum-agent because then all agents on the same curriculum are next to each other in a sorted directory listing.

> What happens if I run the same curriculum/agent pair more than once?

The current time stamped directory structure should still be under the agent-curriculum/ parent directory!

**Review by coreylowman — APPROVED** [review]

**Pull request merged**
