### PR TITLE
upgrade gym dependency

### PR DESCRIPTION
**Pull request by cash**
It is failing some unit tests. Haven't had a chance to look at those.

### CODE REVIEW

**Comment by cash** [comment]
I think they must have removed pygame as a dependency but we require it for cartpole

**Comment by coreylowman** [comment]
I think they moved it to extra installs: https://github.com/openai/gym/blob/master/setup.py#L16

How do you specify that in requirements again? `gym[classic-control]`?

**Comment by cash** [comment]
We only require it for our tests, right?

**Comment by cash** [comment]
ah, nevermind. I see we use it in our curriculums.

**Pull request closed without merging**
